spring.application.name=demo
# 1. Database Connection URL (bewakoof_db ki jagah apne database ka naam likhna)
spring.datasource.url=jdbc:mysql://localhost:3306/bewakoof

# 2. Database Username (Default 'root' hota hai)
spring.datasource.username=root

# 3. Database Password (Jo tumne MySQL install karte waqt set kiya tha)
spring.datasource.password= Aditya@28

# 4. Driver Class Name (MySQL 8+ ke liye standard driver)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 5. Hibernate/JPA Properties
# 'update' se tables automatic ban jayengi database mein agar nahi bani hongi toh
spring.jpa.hibernate.ddl-auto=update

# Console par chalne wali SQL queries ko dekhne ke liye (Debugging mein kaam aayega)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081